language: java

dist: trusty
sudo: required
addons:
  apt:
    packages:

install: true

services:

script:

jdk:
  - oraclejdk8

before_script:

branches:

notifications:
  email: false

after_success:

